import {
  sqliteTable,
  text,
  integer,
  uniqueIndex,
  index,
} from "drizzle-orm/sqlite-core";

/**
 * User-configurable summary presets.
 * Each preset carries a summaryPrompt injected into Step 3 of the research pipeline.
 * Built-in presets (isBuiltin = true) cannot be deleted; only builtin-research-report
 * is also non-editable (enforced at the API layer).
 */
export const summaryPresets = sqliteTable("summary_presets", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(),
  description: text("description"),
  prompt: text("prompt").notNull(),
  isBuiltin: integer("is_builtin", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
});

/**
 * Persisted artifacts generated by the Studio panel (via NotebookLM SDK).
 * Covers all SDK artifact types: audio, quiz, flashcards, report, slide_deck,
 * video, mind_map, infographic, etc.
 * Content is stored as a JSON blob when the artifact reaches READY state.
 */
export const artifacts = sqliteTable(
  "artifacts",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    notebookId: text("notebook_id").notNull(),
    /** The NLM SDK artifact ID used to poll status. */
    artifactId: text("artifact_id").notNull(),
    /** Artifact type string matching StudioPanel ArtifactDef.key */
    artifactType: text("artifact_type").notNull(),
    /** "creating" | "ready" | "failed" */
    state: text("state").notNull().default("creating"),
    /** Display title returned by SDK when ready */
    title: text("title"),
    /** Full artifact content serialised as JSON (populated when state=ready) */
    contentJson: text("content_json"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    notebookIdx: index("idx_artifacts_notebook").on(table.notebookId),
    artifactIdIdx: uniqueIndex("idx_artifacts_artifact_id").on(table.artifactId),
  })
);

/**
 * Unified table for all persisted "output" items:
 *  - entry_type = 'research_report' → locally generated research reports
 *  - entry_type = 'artifact'        → NotebookLM Studio artifacts (quiz, flashcards, audio, etc.)
 *
 * Binary content (audio MP3, slides PDF) is written to the local filesystem under
 * data/files/ and only the relative filename is stored in file_path.
 * Small structured content (quiz questions, flashcards) stays in content_json.
 */
export const reportEntries = sqliteTable(
  "report_entries",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    notebookId: text("notebook_id").notNull(),
    /** 'research_report' | 'artifact' */
    entryType: text("entry_type").notNull(),
    /** Display title */
    title: text("title"),
    /** 'creating' | 'ready' | 'failed' */
    state: text("state").notNull().default("ready"),
    /** Markdown content — research_report only */
    content: text("content"),
    /** Error details when state = 'failed' */
    errorMessage: text("error_message"),
    /** Summary preset used for research_report rows when applicable. */
    presetId: text("preset_id"),
    /** NotebookLM SDK artifact ID — artifact only */
    artifactId: text("artifact_id"),
    /** SDK artifact type string — artifact only */
    artifactType: text("artifact_type"),
    /** Small structured content as JSON (quiz, flashcards, etc.) — artifact only */
    contentJson: text("content_json"),
    /** Relative filename under data/files/ (audio, PDF, etc.) — artifact only */
    filePath: text("file_path"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    notebookIdx: index("idx_report_entries_notebook").on(table.notebookId),
    // Note: the raw SQL CREATE TABLE uses a partial unique index with
    // WHERE artifact_id IS NOT NULL, which Drizzle sqlite-core cannot express.
    // Use a plain index here so drizzle-kit won't generate an incorrect unique constraint.
    artifactIdIdx: index("idx_report_entries_artifact_id").on(table.artifactId),
  })
);

export const researchReports = sqliteTable(
  "research_reports",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    notebookId: text("notebook_id").notNull(),
    title: text("title").notNull(),
    content: text("content"),
    generatedAt: integer("generated_at", { mode: "timestamp" }),
    errorMessage: text("error_message"),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    notebookIdx: index("idx_reports_notebook").on(table.notebookId),
  })
);

export const researchTasks = sqliteTable("research_tasks", {
  id: text("id").primaryKey(),
  notebookUrl: text("notebook_url").notNull(),
  topic: text("topic"),
  status: text("status", {
    enum: ["pending", "generating_questions", "asking", "summarizing", "done", "error"],
  })
    .notNull()
    .default("pending"),
  numQuestions: integer("num_questions").notNull().default(10),
  completedQuestions: integer("completed_questions").notNull().default(0),
  report: text("report"),
  errorMessage: text("error_message"),
  /** Which summary preset was used. null → falls back to builtin-research-report. */
  presetId: text("preset_id").references(() => summaryPresets.id),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  completedAt: integer("completed_at", { mode: "timestamp" }),
});

export const questions = sqliteTable("questions", {
  id: text("id").primaryKey(),
  taskId: text("task_id")
    .notNull()
    .references(() => researchTasks.id),
  orderNum: integer("order_num").notNull(),
  questionText: text("question_text").notNull(),
  answerText: text("answer_text"),
  status: text("status", {
    enum: ["pending", "asking", "done", "error"],
  })
    .notNull()
    .default("pending"),
  errorMessage: text("error_message"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

export const notebookSourceStates = sqliteTable(
  "notebook_source_states",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    notebookId: text("notebook_id").notNull(),
    sourceId: text("source_id").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (table) => ({
    notebookSourceUnique: uniqueIndex("notebook_source_unique").on(
      table.notebookId,
      table.sourceId
    ),
  })
);

export const bookSourceStats = sqliteTable("book_source_stats", {
  sourceId: text("source_id").primaryKey(),
  sourceLabel: text("source_label").notNull(),
  attemptCount: integer("attempt_count").notNull().default(0),
  successCount: integer("success_count").notNull().default(0),
  emptyCount: integer("empty_count").notNull().default(0),
  failureCount: integer("failure_count").notNull().default(0),
  lastStatus: text("last_status").notNull().default("failure"),
  lastError: text("last_error"),
  lastLatencyMs: integer("last_latency_ms"),
  lastSuccessAt: integer("last_success_at", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
});

export const chatMessages = sqliteTable(
  "chat_messages",
  {
    id: text("id")
      .primaryKey()
      .notNull()
      .$defaultFn(() => crypto.randomUUID()),
    notebookId: text("notebook_id").notNull(),
    role: text("role", { enum: ["user", "assistant"] }).notNull(),
    content: text("content").notNull(),
    source: text("source", { enum: ["manual", "research", "book_finder"] }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    notebookIdIdx: index("chat_messages_notebook_id").on(
      table.notebookId,
      table.createdAt
    ),
  })
);
