export {
  askNotebook,
  listNotebooks,
  extractNotebookId,
  getAuthStatus,
  disposeClient,
  // New gateway methods
  getNotebookDetail,
  getNotebookSources,
  getNotebookMessages,
  askNotebookForResearch,
  ensureNotebookAccessible,
  addSourceFromUrl,
  addSourceFromText,
  addSourceFromFile,
  searchWebSources,
  addDiscoveredSources,
  getSourceProcessingStatus,
  // Types
  type AuthStatus,
  type AskResult,
  type NotebookDetail,
  type NotebookSource,
  type NotebookMessage,
  type NotebookMessagesResult,
  type ResearchAskResult,
  type AccessCheckResult,
  type SourceAddResponse,
  type SourceSearchInput,
} from "./client.js";
